import { DeconstructedSong } from '../types/music';

export const PRESET_SONGS: DeconstructedSong[] = [
  {
    id: 'midnight-groove',
    title: 'Midnight Funk Odyssey',
    originalArtist: 'Harmonic DNA Labs',
    genre: 'Nu-Disco / Funk',
    year: '2024',
    description: 'A punchy 118 BPM French-touch groove driven by syncopated Minor 9th and Major 7th chords, an octave-jumping disco bassline, and four-on-the-floor kick.',
    tags: ['Four-on-the-floor', 'Dorian Voicings', '16th Bass Slap', 'Extended 9ths'],
    harmonicDNA: {
      key: 'D',
      scale: 'dorian',
      progression: [
        { root: 'D', quality: 'min9', roman: 'i9', durationBeats: 4, pitches: [50, 53, 57, 60, 64] },
        { root: 'G', quality: '7', roman: 'IV7', durationBeats: 4, pitches: [55, 59, 62, 65] },
        { root: 'C', quality: 'maj7', roman: 'bVIImaj7', durationBeats: 4, pitches: [48, 52, 55, 59] },
        { root: 'A', quality: '7', roman: 'V7', durationBeats: 4, pitches: [45, 49, 52, 55] },
      ],
      harmonicComplexity: 78,
      harmonicRhythm: '1 chord/bar',
      voiceLeadingTension: 62,
    },
    rhythmicDNA: {
      bpm: 118,
      timeSignature: [4, 4],
      swingPercent: 35,
      syncopationScore: 84,
      grooveFeel: 'funky-16th',
      accentGrid: [1.0, 0.3, 0.7, 0.3, 0.9, 0.2, 0.8, 0.4, 1.0, 0.3, 0.7, 0.3, 0.9, 0.2, 0.8, 0.5],
      humanizeTimingMs: 8,
    },
    melodicDNA: {
      range: { minPitch: 62, maxPitch: 79 },
      contour: 'wave',
      motifRepetition: 82,
      stepVsLeapRatio: 65,
      notes: [
        { pitch: 69, noteName: 'A4', startStep: 0, durationSteps: 2, velocity: 100 },
        { pitch: 72, noteName: 'C5', startStep: 2, durationSteps: 2, velocity: 92 },
        { pitch: 74, noteName: 'D5', startStep: 4, durationSteps: 4, velocity: 105 },
        { pitch: 72, noteName: 'C5', startStep: 8, durationSteps: 2, velocity: 88 },
        { pitch: 69, noteName: 'A4', startStep: 10, durationSteps: 2, velocity: 94 },
        { pitch: 67, noteName: 'G4', startStep: 12, durationSteps: 4, velocity: 85 },
      ],
    },
    stems: {
      lead: [
        { pitch: 69, noteName: 'A4', startStep: 0, durationSteps: 2, velocity: 100 },
        { pitch: 72, noteName: 'C5', startStep: 2, durationSteps: 2, velocity: 92 },
        { pitch: 74, noteName: 'D5', startStep: 4, durationSteps: 4, velocity: 105 },
        { pitch: 72, noteName: 'C5', startStep: 8, durationSteps: 2, velocity: 88 },
        { pitch: 69, noteName: 'A4', startStep: 10, durationSteps: 2, velocity: 94 },
        { pitch: 67, noteName: 'G4', startStep: 12, durationSteps: 4, velocity: 85 },
      ],
      chords: [
        { pitch: 50, noteName: 'D3', startStep: 0, durationSteps: 4, velocity: 80 },
        { pitch: 53, noteName: 'F3', startStep: 0, durationSteps: 4, velocity: 75 },
        { pitch: 57, noteName: 'A3', startStep: 0, durationSteps: 4, velocity: 78 },
        { pitch: 60, noteName: 'C4', startStep: 0, durationSteps: 4, velocity: 72 },
        { pitch: 64, noteName: 'E4', startStep: 0, durationSteps: 4, velocity: 70 },
        { pitch: 55, noteName: 'G3', startStep: 4, durationSteps: 4, velocity: 82 },
        { pitch: 59, noteName: 'B3', startStep: 4, durationSteps: 4, velocity: 75 },
        { pitch: 62, noteName: 'D4', startStep: 4, durationSteps: 4, velocity: 77 },
        { pitch: 65, noteName: 'F4', startStep: 4, durationSteps: 4, velocity: 74 },
        { pitch: 48, noteName: 'C3', startStep: 8, durationSteps: 4, velocity: 80 },
        { pitch: 52, noteName: 'E3', startStep: 8, durationSteps: 4, velocity: 75 },
        { pitch: 55, noteName: 'G3', startStep: 8, durationSteps: 4, velocity: 76 },
        { pitch: 59, noteName: 'B3', startStep: 8, durationSteps: 4, velocity: 72 },
        { pitch: 45, noteName: 'A2', startStep: 12, durationSteps: 4, velocity: 85 },
        { pitch: 49, noteName: 'C#3', startStep: 12, durationSteps: 4, velocity: 80 },
        { pitch: 52, noteName: 'E3', startStep: 12, durationSteps: 4, velocity: 78 },
        { pitch: 55, noteName: 'G3', startStep: 12, durationSteps: 4, velocity: 75 },
      ],
      bass: [
        { pitch: 38, noteName: 'D2', startStep: 0, durationSteps: 2, velocity: 110 },
        { pitch: 50, noteName: 'D3', startStep: 2, durationSteps: 2, velocity: 95 },
        { pitch: 43, noteName: 'G2', startStep: 4, durationSteps: 2, velocity: 110 },
        { pitch: 55, noteName: 'G3', startStep: 6, durationSteps: 2, velocity: 95 },
        { pitch: 36, noteName: 'C2', startStep: 8, durationSteps: 2, velocity: 110 },
        { pitch: 48, noteName: 'C3', startStep: 10, durationSteps: 2, velocity: 95 },
        { pitch: 33, noteName: 'A1', startStep: 12, durationSteps: 2, velocity: 115 },
        { pitch: 45, noteName: 'A2', startStep: 14, durationSteps: 2, velocity: 100 },
      ],
      drums: {
        kick: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
        snare: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
        hihat: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
        perc: [false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, false],
      },
    },
  },
  {
    id: 'neon-horizon',
    title: 'Neon Outrun 1984',
    originalArtist: 'Retrowave Collective',
    genre: 'Synthwave / Retrowave',
    year: '1984',
    description: 'A driving 126 BPM retro-futuristic synthwave track with soaring octave saw bass, gated reverb drums, and nostalgic minor-scale hooks.',
    tags: ['Pumping Octaves', 'Sawtooth Lead', 'Minor Key', 'Gated Snares'],
    harmonicDNA: {
      key: 'F#',
      scale: 'minor',
      progression: [
        { root: 'F#', quality: 'min', roman: 'i', durationBeats: 4, pitches: [42, 45, 49] },
        { root: 'D', quality: 'maj', roman: 'VI', durationBeats: 4, pitches: [38, 42, 45] },
        { root: 'A', quality: 'maj', roman: 'III', durationBeats: 4, pitches: [45, 49, 52] },
        { root: 'E', quality: 'maj', roman: 'VII', durationBeats: 4, pitches: [40, 44, 47] },
      ],
      harmonicComplexity: 58,
      harmonicRhythm: '1 chord/bar',
      voiceLeadingTension: 55,
    },
    rhythmicDNA: {
      bpm: 126,
      timeSignature: [4, 4],
      swingPercent: 0,
      syncopationScore: 40,
      grooveFeel: 'straight',
      accentGrid: [1.0, 0.4, 0.7, 0.4, 0.9, 0.4, 0.7, 0.4, 1.0, 0.4, 0.7, 0.4, 0.9, 0.4, 0.7, 0.4],
      humanizeTimingMs: 3,
    },
    melodicDNA: {
      range: { minPitch: 66, maxPitch: 81 },
      contour: 'arch',
      motifRepetition: 90,
      stepVsLeapRatio: 75,
      notes: [
        { pitch: 66, noteName: 'F#4', startStep: 0, durationSteps: 4, velocity: 105 },
        { pitch: 69, noteName: 'A4', startStep: 4, durationSteps: 2, velocity: 95 },
        { pitch: 73, noteName: 'C#5', startStep: 6, durationSteps: 2, velocity: 100 },
        { pitch: 76, noteName: 'E5', startStep: 8, durationSteps: 4, velocity: 110 },
        { pitch: 73, noteName: 'C#5', startStep: 12, durationSteps: 4, velocity: 95 },
      ],
    },
    stems: {
      lead: [
        { pitch: 66, noteName: 'F#4', startStep: 0, durationSteps: 4, velocity: 105 },
        { pitch: 69, noteName: 'A4', startStep: 4, durationSteps: 2, velocity: 95 },
        { pitch: 73, noteName: 'C#5', startStep: 6, durationSteps: 2, velocity: 100 },
        { pitch: 76, noteName: 'E5', startStep: 8, durationSteps: 4, velocity: 110 },
        { pitch: 73, noteName: 'C#5', startStep: 12, durationSteps: 4, velocity: 95 },
      ],
      chords: [
        { pitch: 54, noteName: 'F#3', startStep: 0, durationSteps: 4, velocity: 85 },
        { pitch: 57, noteName: 'A3', startStep: 0, durationSteps: 4, velocity: 80 },
        { pitch: 61, noteName: 'C#4', startStep: 0, durationSteps: 4, velocity: 82 },
        { pitch: 50, noteName: 'D3', startStep: 4, durationSteps: 4, velocity: 85 },
        { pitch: 54, noteName: 'F#3', startStep: 4, durationSteps: 4, velocity: 80 },
        { pitch: 57, noteName: 'A3', startStep: 4, durationSteps: 4, velocity: 82 },
        { pitch: 45, noteName: 'A2', startStep: 8, durationSteps: 4, velocity: 85 },
        { pitch: 49, noteName: 'C#3', startStep: 8, durationSteps: 4, velocity: 80 },
        { pitch: 52, noteName: 'E3', startStep: 8, durationSteps: 4, velocity: 82 },
        { pitch: 40, noteName: 'E2', startStep: 12, durationSteps: 4, velocity: 85 },
        { pitch: 44, noteName: 'G#2', startStep: 12, durationSteps: 4, velocity: 80 },
        { pitch: 47, noteName: 'B2', startStep: 12, durationSteps: 4, velocity: 82 },
      ],
      bass: [
        { pitch: 30, noteName: 'F#1', startStep: 0, durationSteps: 1, velocity: 105 },
        { pitch: 42, noteName: 'F#2', startStep: 1, durationSteps: 1, velocity: 95 },
        { pitch: 30, noteName: 'F#1', startStep: 2, durationSteps: 1, velocity: 100 },
        { pitch: 42, noteName: 'F#2', startStep: 3, durationSteps: 1, velocity: 95 },
        { pitch: 26, noteName: 'D1', startStep: 4, durationSteps: 1, velocity: 105 },
        { pitch: 38, noteName: 'D2', startStep: 5, durationSteps: 1, velocity: 95 },
        { pitch: 26, noteName: 'D1', startStep: 6, durationSteps: 1, velocity: 100 },
        { pitch: 38, noteName: 'D2', startStep: 7, durationSteps: 1, velocity: 95 },
        { pitch: 33, noteName: 'A1', startStep: 8, durationSteps: 1, velocity: 105 },
        { pitch: 45, noteName: 'A2', startStep: 9, durationSteps: 1, velocity: 95 },
        { pitch: 33, noteName: 'A1', startStep: 10, durationSteps: 1, velocity: 100 },
        { pitch: 45, noteName: 'A2', startStep: 11, durationSteps: 1, velocity: 95 },
        { pitch: 28, noteName: 'E1', startStep: 12, durationSteps: 1, velocity: 105 },
        { pitch: 40, noteName: 'E2', startStep: 13, durationSteps: 1, velocity: 95 },
        { pitch: 28, noteName: 'E1', startStep: 14, durationSteps: 1, velocity: 100 },
        { pitch: 40, noteName: 'E2', startStep: 15, durationSteps: 1, velocity: 95 },
      ],
      drums: {
        kick: [true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false],
        snare: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
        hihat: [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        perc: [false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true],
      },
    },
  },
  {
    id: 'rainy-cafe',
    title: 'Rainy Window Chillhop',
    originalArtist: 'Lo-Fi Study Beats',
    genre: 'Lofi Hip Hop / Chillhop',
    year: '2023',
    description: 'Laid-back 82 BPM boom-bap swing with vintage Rhodes major 9th voicings, warm sub-bass, vinyl flutter, and subtle acoustic snares.',
    tags: ['Boom Bap', 'Heavy Swing', 'Drop-2 Rhodes', 'Warm Sub'],
    harmonicDNA: {
      key: 'Eb',
      scale: 'major',
      progression: [
        { root: 'Eb', quality: 'maj7', roman: 'Imaj7', durationBeats: 4, pitches: [51, 55, 58, 62] },
        { root: 'C', quality: 'min7', roman: 'vi7', durationBeats: 4, pitches: [48, 51, 55, 58] },
        { root: 'F', quality: 'min9', roman: 'ii9', durationBeats: 4, pitches: [53, 56, 60, 63, 67] },
        { root: 'Bb', quality: '7', roman: 'V7', durationBeats: 4, pitches: [46, 50, 53, 56] },
      ],
      harmonicComplexity: 85,
      harmonicRhythm: '1 chord/bar',
      voiceLeadingTension: 45,
    },
    rhythmicDNA: {
      bpm: 82,
      timeSignature: [4, 4],
      swingPercent: 64,
      syncopationScore: 72,
      grooveFeel: 'laidback-swing',
      accentGrid: [1.0, 0.2, 0.6, 0.5, 0.8, 0.2, 0.7, 0.4, 0.9, 0.2, 0.6, 0.5, 0.8, 0.3, 0.7, 0.4],
      humanizeTimingMs: 14,
    },
    melodicDNA: {
      range: { minPitch: 62, maxPitch: 75 },
      contour: 'descending',
      motifRepetition: 70,
      stepVsLeapRatio: 80,
      notes: [
        { pitch: 70, noteName: 'Bb4', startStep: 1, durationSteps: 3, velocity: 85 },
        { pitch: 67, noteName: 'G4', startStep: 4, durationSteps: 2, velocity: 78 },
        { pitch: 65, noteName: 'F4', startStep: 6, durationSteps: 2, velocity: 80 },
        { pitch: 63, noteName: 'Eb4', startStep: 8, durationSteps: 4, velocity: 90 },
      ],
    },
    stems: {
      lead: [
        { pitch: 70, noteName: 'Bb4', startStep: 1, durationSteps: 3, velocity: 85 },
        { pitch: 67, noteName: 'G4', startStep: 4, durationSteps: 2, velocity: 78 },
        { pitch: 65, noteName: 'F4', startStep: 6, durationSteps: 2, velocity: 80 },
        { pitch: 63, noteName: 'Eb4', startStep: 8, durationSteps: 4, velocity: 90 },
      ],
      chords: [
        { pitch: 51, noteName: 'Eb3', startStep: 0, durationSteps: 4, velocity: 72 },
        { pitch: 55, noteName: 'G3', startStep: 0, durationSteps: 4, velocity: 68 },
        { pitch: 58, noteName: 'Bb3', startStep: 0, durationSteps: 4, velocity: 70 },
        { pitch: 62, noteName: 'D4', startStep: 0, durationSteps: 4, velocity: 66 },
        { pitch: 48, noteName: 'C3', startStep: 4, durationSteps: 4, velocity: 72 },
        { pitch: 51, noteName: 'Eb3', startStep: 4, durationSteps: 4, velocity: 68 },
        { pitch: 55, noteName: 'G3', startStep: 4, durationSteps: 4, velocity: 70 },
        { pitch: 58, noteName: 'Bb3', startStep: 4, durationSteps: 4, velocity: 65 },
        { pitch: 53, noteName: 'F3', startStep: 8, durationSteps: 4, velocity: 74 },
        { pitch: 56, noteName: 'Ab3', startStep: 8, durationSteps: 4, velocity: 68 },
        { pitch: 60, noteName: 'C4', startStep: 8, durationSteps: 4, velocity: 70 },
        { pitch: 63, noteName: 'Eb4', startStep: 8, durationSteps: 4, velocity: 66 },
        { pitch: 67, noteName: 'G4', startStep: 8, durationSteps: 4, velocity: 65 },
        { pitch: 46, noteName: 'Bb2', startStep: 12, durationSteps: 4, velocity: 75 },
        { pitch: 50, noteName: 'D3', startStep: 12, durationSteps: 4, velocity: 70 },
        { pitch: 53, noteName: 'F3', startStep: 12, durationSteps: 4, velocity: 72 },
        { pitch: 56, noteName: 'Ab3', startStep: 12, durationSteps: 4, velocity: 68 },
      ],
      bass: [
        { pitch: 39, noteName: 'Eb2', startStep: 0, durationSteps: 4, velocity: 90 },
        { pitch: 36, noteName: 'C2', startStep: 4, durationSteps: 4, velocity: 90 },
        { pitch: 41, noteName: 'F2', startStep: 8, durationSteps: 4, velocity: 92 },
        { pitch: 34, noteName: 'Bb1', startStep: 12, durationSteps: 4, velocity: 95 },
      ],
      drums: {
        kick: [true, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false],
        snare: [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
        hihat: [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
        perc: [false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false],
      },
    },
  },
  {
    id: 'bossa-breeze',
    title: 'Ipanema Sunbreak',
    originalArtist: 'Rio Jazz Quartet',
    genre: 'Bossa Nova / Samba',
    year: '1967',
    description: 'Breezy 124 BPM bossa nova featuring classic Brazilian clave syncopation, gentle walking root-fifth bassline, and colorful altered dominance.',
    tags: ['Brazilian Clave', 'Walking 5ths', 'Half-Diminished', 'Acoustic Strum'],
    harmonicDNA: {
      key: 'F',
      scale: 'major',
      progression: [
        { root: 'F', quality: 'maj7', roman: 'Imaj7', durationBeats: 4, pitches: [53, 57, 60, 64] },
        { root: 'G', quality: '7', roman: 'II7', durationBeats: 4, pitches: [55, 59, 62, 65] },
        { root: 'G', quality: 'min7', roman: 'ii7', durationBeats: 4, pitches: [55, 58, 62, 65] },
        { root: 'C', quality: '7', roman: 'V7', durationBeats: 4, pitches: [48, 52, 55, 58] },
      ],
      harmonicComplexity: 74,
      harmonicRhythm: '1 chord/bar',
      voiceLeadingTension: 58,
    },
    rhythmicDNA: {
      bpm: 124,
      timeSignature: [4, 4],
      swingPercent: 30,
      syncopationScore: 88,
      grooveFeel: 'bossa-clave',
      accentGrid: [1.0, 0.2, 0.3, 0.8, 0.2, 0.7, 0.2, 0.3, 0.9, 0.2, 0.7, 0.2, 0.8, 0.2, 0.3, 0.5],
      humanizeTimingMs: 10,
    },
    melodicDNA: {
      range: { minPitch: 60, maxPitch: 74 },
      contour: 'wave',
      motifRepetition: 75,
      stepVsLeapRatio: 70,
      notes: [
        { pitch: 65, noteName: 'F4', startStep: 0, durationSteps: 3, velocity: 85 },
        { pitch: 64, noteName: 'E4', startStep: 3, durationSteps: 2, velocity: 80 },
        { pitch: 62, noteName: 'D4', startStep: 5, durationSteps: 3, velocity: 82 },
        { pitch: 65, noteName: 'F4', startStep: 8, durationSteps: 2, velocity: 88 },
        { pitch: 67, noteName: 'G4', startStep: 10, durationSteps: 4, velocity: 90 },
      ],
    },
    stems: {
      lead: [
        { pitch: 65, noteName: 'F4', startStep: 0, durationSteps: 3, velocity: 85 },
        { pitch: 64, noteName: 'E4', startStep: 3, durationSteps: 2, velocity: 80 },
        { pitch: 62, noteName: 'D4', startStep: 5, durationSteps: 3, velocity: 82 },
        { pitch: 65, noteName: 'F4', startStep: 8, durationSteps: 2, velocity: 88 },
        { pitch: 67, noteName: 'G4', startStep: 10, durationSteps: 4, velocity: 90 },
      ],
      chords: [
        { pitch: 53, noteName: 'F3', startStep: 0, durationSteps: 2, velocity: 70 },
        { pitch: 57, noteName: 'A3', startStep: 0, durationSteps: 2, velocity: 72 },
        { pitch: 60, noteName: 'C4', startStep: 0, durationSteps: 2, velocity: 68 },
        { pitch: 64, noteName: 'E4', startStep: 0, durationSteps: 2, velocity: 65 },
        { pitch: 55, noteName: 'G3', startStep: 4, durationSteps: 2, velocity: 72 },
        { pitch: 59, noteName: 'B3', startStep: 4, durationSteps: 2, velocity: 70 },
        { pitch: 62, noteName: 'D4', startStep: 4, durationSteps: 2, velocity: 68 },
        { pitch: 65, noteName: 'F4', startStep: 4, durationSteps: 2, velocity: 66 },
        { pitch: 55, noteName: 'G3', startStep: 8, durationSteps: 2, velocity: 70 },
        { pitch: 58, noteName: 'Bb3', startStep: 8, durationSteps: 2, velocity: 68 },
        { pitch: 62, noteName: 'D4', startStep: 8, durationSteps: 2, velocity: 66 },
        { pitch: 65, noteName: 'F4', startStep: 8, durationSteps: 2, velocity: 64 },
        { pitch: 48, noteName: 'C3', startStep: 12, durationSteps: 2, velocity: 75 },
        { pitch: 52, noteName: 'E3', startStep: 12, durationSteps: 2, velocity: 70 },
        { pitch: 55, noteName: 'G3', startStep: 12, durationSteps: 2, velocity: 72 },
        { pitch: 58, noteName: 'Bb3', startStep: 12, durationSteps: 2, velocity: 68 },
      ],
      bass: [
        { pitch: 41, noteName: 'F2', startStep: 0, durationSteps: 2, velocity: 95 },
        { pitch: 48, noteName: 'C3', startStep: 2, durationSteps: 2, velocity: 85 },
        { pitch: 43, noteName: 'G2', startStep: 4, durationSteps: 2, velocity: 95 },
        { pitch: 50, noteName: 'D3', startStep: 6, durationSteps: 2, velocity: 85 },
        { pitch: 43, noteName: 'G2', startStep: 8, durationSteps: 2, velocity: 95 },
        { pitch: 50, noteName: 'D3', startStep: 10, durationSteps: 2, velocity: 85 },
        { pitch: 36, noteName: 'C2', startStep: 12, durationSteps: 2, velocity: 95 },
        { pitch: 43, noteName: 'G2', startStep: 14, durationSteps: 2, velocity: 85 },
      ],
      drums: {
        kick: [true, false, false, false, false, false, true, false, true, false, false, false, false, false, true, false],
        snare: [false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false],
        hihat: [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
        perc: [false, false, false, false, true, false, false, true, false, false, false, true, false, true, false, false],
      },
    },
  },
];
